In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [3]:
data

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.preprocessing import LabelEncoder

In [5]:
le = LabelEncoder()

In [6]:
data['label'] = le.fit_transform(data['label'])

In [7]:
data

sep_l  sep_w  pet_l  pet_w  label
0      5.1    3.5    1.4    0.2      0
1      4.9    3.0    1.4    0.2      0
2      4.7    3.2    1.3    0.2      0
3      4.6    3.1    1.5    0.2      0
4      5.0    3.6    1.4    0.2      0
..     ...    ...    ...    ...    ...
145    6.7    3.0    5.2    2.3      2
146    6.3    2.5    5.0    1.9      2
147    6.5    3.0    5.2    2.0      2
148    6.2    3.4    5.4    2.3      2
149    5.9    3.0    5.1    1.8      2

[150 rows x 5 columns]

In [8]:
x = data.iloc[:,0:4].values

In [9]:
x 

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = data.iloc[:,4].values

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
X_train.shape

(120, 4)

In [14]:
X_test.shape

(30, 4)

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
model = Sequential([
    Dense(8,input_dim=4,activation='relu'),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax'),
])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 8)                 72        
                                                                 
 dense_3 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [19]:
model.fit(X_train,y_train,epochs=50)

Epoch 1/50
4/4 [==============================] - 1s 4ms/step - loss: 1.1781 - accuracy: 0.3083
Epoch 2/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1596 - accuracy: 0.3083
Epoch 3/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1458 - accuracy: 0.3083
Epoch 4/50
4/4 [==============================] - 0s 3ms/step - loss: 1.1324 - accuracy: 0.3083
Epoch 5/50
4/4 [==============================] - 0s 3ms/step - loss: 1.1208 - accuracy: 0.3083
Epoch 6/50
4/4 [==============================] - 0s 3ms/step - loss: 1.1124 - accuracy: 0.3083
Epoch 7/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1057 - accuracy: 0.3083
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 1.0982 - accuracy: 0.3083
Epoch 9/50
4/4 [==============================] - 0s 3ms/step - loss: 1.0934 - accuracy: 0.3083
Epoch 10/50
4/4 [==============================] - 0s 3ms/step - loss: 1.0890 - accuracy: 0.3083
Epoch 11/50
4/4 [======================

In [20]:
pred = model.predict(X_test)

1/1 [==============================] - 0s 125ms/step


In [21]:
pred.shape

(30, 3)

In [22]:
np.argmax(pred,axis=1)

array([2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 2, 0], dtype=int64)

In [23]:
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
confusion_matrix(y_test,np.argmax(pred,axis=1))

array([[11,  0,  0],
       [ 0,  0, 13],
       [ 0,  0,  6]], dtype=int64)

In [25]:
print(classification_report(y_test,np.argmax(pred,axis=1)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.00      0.00      0.00        13
           2       0.32      1.00      0.48         6

    accuracy                           0.57        30
   macro avg       0.44      0.67      0.49        30
weighted avg       0.43      0.57      0.46        30



C:\Users\VICTUS\.conda\envs\deepl\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\VICTUS\.conda\envs\deepl\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\VICTUS\.conda\envs\deepl\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
