In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
data = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])
data

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

In [4]:
y = data['label']

In [5]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: label, Length: 150, dtype: object

In [6]:
y = np.array(y).reshape(-1,1)

In [7]:
y = ohe.fit_transform(y)

C:\Users\VICTUS\.conda\envs\deepl\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [8]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [9]:
X = data.iloc[:,0:4].values

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape

(120, 4)

In [13]:
X_test.shape

(30, 4)

In [14]:
from keras.models import Sequential
from keras.layers import Dense

In [15]:
model = Sequential([
    Dense(8,input_dim=4,activation='relu'),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax'),
])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 8)                 72        
                                                                 
 dense_3 (Dense)             (None, 3)                 27        
                                                                 
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [18]:
model.fit(X_train,y_train,epochs=50)

Epoch 1/50
4/4 [==============================] - 1s 2ms/step - loss: 1.3921 - accuracy: 0.3083
Epoch 2/50
4/4 [==============================] - 0s 3ms/step - loss: 1.2979 - accuracy: 0.3083
Epoch 3/50
4/4 [==============================] - 0s 3ms/step - loss: 1.2312 - accuracy: 0.3083
Epoch 4/50
4/4 [==============================] - 0s 3ms/step - loss: 1.1840 - accuracy: 0.2917
Epoch 5/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1440 - accuracy: 0.2667
Epoch 6/50
4/4 [==============================] - 0s 4ms/step - loss: 1.1099 - accuracy: 0.1583
Epoch 7/50
4/4 [==============================] - 0s 4ms/step - loss: 1.0872 - accuracy: 0.1000
Epoch 8/50
4/4 [==============================] - 0s 3ms/step - loss: 1.0647 - accuracy: 0.1750
Epoch 9/50
4/4 [==============================] - 0s 4ms/step - loss: 1.0441 - accuracy: 0.1917
Epoch 10/50
4/4 [==============================] - 0s 4ms/step - loss: 1.0277 - accuracy: 0.2083
Epoch 11/50
4/4 [======================

In [19]:
pred = model.predict(X_test)

1/1 [==============================] - 0s 90ms/step


In [20]:
pred.round(2)

array([[0.02, 0.38, 0.59],
       [0.04, 0.4 , 0.56],
       [0.8 , 0.11, 0.09],
       [0.  , 0.33, 0.67],
       [0.77, 0.13, 0.1 ],
       [0.01, 0.36, 0.63],
       [0.77, 0.13, 0.1 ],
       [0.04, 0.39, 0.57],
       [0.03, 0.38, 0.59],
       [0.08, 0.4 , 0.52],
       [0.01, 0.35, 0.64],
       [0.06, 0.4 , 0.54],
       [0.03, 0.39, 0.58],
       [0.03, 0.39, 0.57],
       [0.03, 0.39, 0.58],
       [0.73, 0.15, 0.12],
       [0.04, 0.4 , 0.56],
       [0.03, 0.4 , 0.57],
       [0.75, 0.14, 0.11],
       [0.79, 0.12, 0.09],
       [0.03, 0.39, 0.58],
       [0.05, 0.4 , 0.55],
       [0.68, 0.17, 0.14],
       [0.73, 0.15, 0.12],
       [0.03, 0.39, 0.58],
       [0.75, 0.14, 0.11],
       [0.77, 0.13, 0.1 ],
       [0.05, 0.4 , 0.55],
       [0.11, 0.4 , 0.49],
       [0.76, 0.13, 0.1 ]], dtype=float32)

In [21]:
np.argmax(pred,axis=1)

array([2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 2, 2,
       0, 0, 2, 0, 0, 2, 2, 0], dtype=int64)